import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "#f2f5fa",
  },
  backButton: {
    position: "absolute",
    top: 38,
    left: 18,
    zIndex: 10,
    backgroundColor: "#e0e7ef",
    borderRadius: 24,
    padding: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  scrollContainer: {
    paddingTop: 60,
    paddingBottom: 32,
    alignItems: "center",
  },
  content: {
    width: "92%",
    backgroundColor: "#fff",
    borderRadius: 22,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.09,
    shadowRadius: 12,
    elevation: 6,
    marginBottom: 24,
  },
  image: {
    width: 210,
    height: 300,
    borderRadius: 18,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: "#dbeafe",
    backgroundColor: "#eaf1fb",
  },
  titulo: {
    fontSize: 23,
    fontWeight: "700",
    color: "#26324d",
    marginBottom: 4,
    textAlign: "center",
    letterSpacing: 0.2,
  },
  preco: {
    fontSize: 19,
    color: "#3887fe",
    fontWeight: "bold",
    marginBottom: 14,
    letterSpacing: 0.3,
  },
  subtitulo: {
    fontSize: 15,
    color: "#5a6a90",
    fontWeight: "600",
    marginTop: 14,
    marginBottom: 3,
    alignSelf: "flex-start",
    letterSpacing: 0.1,
  },
  descricao: {
    fontSize: 15,
    color: "#3a4256",
    textAlign: "justify",
    marginBottom: 10,
    lineHeight: 22,
    borderRadius: 8,
    backgroundColor: "#f6f8fc",
    padding: 8,
    width: "100%",
  },
  plataforma: {
    fontSize: 15,
    color: "#3887fe",
    marginBottom: 16,
    alignSelf: "flex-start",
    backgroundColor: "#eaf1fb",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: "hidden",
  },
  botaoCompra: {
    backgroundColor: "#3887fe",
    paddingVertical: 13,
    paddingHorizontal: 32,
    borderRadius: 12,
    marginTop: 18,
    marginBottom: 10,
    width: "100%",
    alignItems: "center",
    elevation: 2,
    shadowColor: "#3887fe",
    shadowOpacity: 0.15,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  textoBotao: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  botaoCarrinho: {
    backgroundColor: "#fff",
    borderWidth: 1.5,
    borderColor: "#3887fe",
    paddingVertical: 13,
    paddingHorizontal: 32,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
    elevation: 1,
    marginBottom: 8,
  },
  textoBotaoSecundario: {
    color: "#3887fe",
    fontSize: 16,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
});

export default styles;